# Generated by Django 5.0.2 on 2024-02-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_book_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_img',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
