# Generated by Django 5.0.2 on 2024-02-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug_book',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
