# Generated by Django 5.0.2 on 2024-02-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_slug_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='slug_book',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
