# Generated by Django 5.0.2 on 2024-02-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_rename_slug_book_books_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="slug",
            field=models.SlugField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="book_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="books.books"
            ),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="order_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="books.orders"
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="customer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="books.cumtomers"
            ),
        ),
    ]
