# Generated by Django 5.0.2 on 2024-02-17 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_alter_genre_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="genre",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.PROTECT,
                to="books.genre",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(default="", max_length=255),
        ),
    ]
